// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPv7RCyydf1sM8BzzH_nIm3NO9jktbzV4',
    appId: '1:161456697934:web:fdb650fef1553381da091f',
    messagingSenderId: '161456697934',
    projectId: 'project-firebase-61026',
    authDomain: 'project-firebase-61026.firebaseapp.com',
    storageBucket: 'project-firebase-61026.firebasestorage.app',
    measurementId: 'G-61FLLJWLVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoXzrWEiSiJUlODU9qgGP4W8GS6qCU-zU',
    appId: '1:161456697934:android:f2a60edf0b18f537da091f',
    messagingSenderId: '161456697934',
    projectId: 'project-firebase-61026',
    storageBucket: 'project-firebase-61026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKhgqiOdpKGi0CH_n827xxKQwAuB8NUT4',
    appId: '1:161456697934:ios:03ef74617a9bb879da091f',
    messagingSenderId: '161456697934',
    projectId: 'project-firebase-61026',
    storageBucket: 'project-firebase-61026.firebasestorage.app',
    iosBundleId: 'com.example.projectFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKhgqiOdpKGi0CH_n827xxKQwAuB8NUT4',
    appId: '1:161456697934:ios:03ef74617a9bb879da091f',
    messagingSenderId: '161456697934',
    projectId: 'project-firebase-61026',
    storageBucket: 'project-firebase-61026.firebasestorage.app',
    iosBundleId: 'com.example.projectFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPv7RCyydf1sM8BzzH_nIm3NO9jktbzV4',
    appId: '1:161456697934:web:f42765aee4492532da091f',
    messagingSenderId: '161456697934',
    projectId: 'project-firebase-61026',
    authDomain: 'project-firebase-61026.firebaseapp.com',
    storageBucket: 'project-firebase-61026.firebasestorage.app',
    measurementId: 'G-S7JPM9EL4L',
  );
}
